[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

# Configurações específicas por módulo
[[tool.mypy.overrides]]
module = "peripherals.services.print_service"
# Ignorar erros de atributos em Printer pois na runtime será BasePeripheralDriver
disable_error_code = ["attr-defined"]

[[tool.mypy.overrides]]
module = "peripherals.services.peripheral_service"
# Ignorar incompatibilidades de tipo entre Printer e BasePeripheralDriver
disable_error_code = ["assignment"]

[[tool.mypy.overrides]]
module = "peripherals.services.peripheral_db_service"
# Ignorar incompatibilidades de retorno
disable_error_code = ["return-value"]

[[tool.mypy.overrides]]
module = "peripherals.drivers.*"
# Ignorar erros de union-attr para conexões que podem ser None
disable_error_code = ["union-attr"]

[[tool.mypy.overrides]]
module = "peripherals.router.*"
# Ignorar erros de argumentos em routers
disable_error_code = ["arg-type", "dict-item"]